version: '3.7'

services:
  eat-vegetal-api:
    image: maxolidean/eat-vegetal-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      API_PORT: 8080
    command: ./node_modules/.bin/nodemon -L -x 'node --inspect=0.0.0.0:8180 src/server.js || touch src/server.js'
    ports:
      - 8080:8080
      - 8180:8180
    volumes:
      - ./logs:/c/code/eat-vegetal-api/src/api/logs
      - ./src:/c/code/eat-vegetal-api/src
